# Generated by Django 4.2.3 on 2023-07-18 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('place_name', models.CharField(max_length=100)),
                ('location_x', models.DecimalField(decimal_places=8, max_digits=9)),
                ('location_y', models.DecimalField(decimal_places=8, max_digits=9)),
                ('imageUrl', models.TextField()),
                ('description', models.TextField()),
                ('tickerPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageUrlString', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EventFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDeviceId', models.TextField()),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventfinder.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userDeviceId', models.TextField()),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventfinder.event')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventfinder.eventcategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='countyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventfinder.county'),
        ),
    ]
