# Generated by Django 4.2.3 on 2023-07-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventfinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventFavorites',
            new_name='EventFavorite',
        ),
    ]
