# Generated by Django 4.2.3 on 2023-07-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventfinder', '0003_rename_tickerprice_event_ticket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='ticket',
            new_name='ticketPrice',
        ),
    ]
