# Generated by Django 4.2.3 on 2023-08-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventfinder', '0003_event_infav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='inFav',
        ),
    ]
