# Generated by Django 4.2.3 on 2023-07-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventfinder', '0004_rename_ticket_event_ticketprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticketPrice',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
