# Generated by Django 4.2.3 on 2023-07-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventfinder', '0005_alter_event_ticketprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_x',
            field=models.DecimalField(decimal_places=8, max_digits=9999),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_y',
            field=models.DecimalField(decimal_places=8, max_digits=9999),
        ),
    ]
